#1. Calculate the number of orders per month in 2018
SELECT 
    MONTH(order_purchase_timestamp) AS month,
    COUNT(order_id) AS total_orders
FROM
    orders
WHERE
    YEAR(order_purchase_timestamp) = 2018
GROUP BY MONTH(order_purchase_timestamp)
ORDER BY month;
#2 Find the average number of products per order, grouped by customer city.
   SELECT 
    c.customer_city,
    AVG(order_product_count) AS avg_products_per_order
FROM
    (SELECT 
        o.order_id,
            o.customer_id,
            COUNT(oi.product_id) AS order_product_count
    FROM
        orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.order_id , o.customer_id) t
        JOIN
    customers c ON t.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY avg_products_per_order DESC;

#3Calculate the percentage of total revenue contributed by each product category.
SELECT 
    p.product_category AS category,
    SUM(oi.price) AS category_revenue,
    ROUND(SUM(oi.price) * 100.0 / (SELECT 
                    SUM(price)
                FROM
                    order_items),
            2) AS revenue_percentage
FROM
    order_items oi
        JOIN
    products p ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY revenue_percentage DESC;
#4 Identify the correlation between product price and the number of times a product has been purchased
SELECT 
    oi.product_id,
    AVG(oi.price) AS avg_price,
    COUNT(oi.product_id) AS purchase_count
FROM order_items oi
GROUP BY oi.product_id;
#5 Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT 
    oi.seller_id,
    SUM(oi.price) AS total_revenue,
    RANK() OVER (ORDER BY SUM(oi.price) DESC) AS revenue_rank
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_revenue DESC;